create table if not exists public.rorisk_coinflip_games (
  uuid uuid primary key default gen_random_uuid(),
  game_id bigint generated by default as identity unique,
  creator_uuid uuid not null references public.rorisk_users(uuid) on delete cascade,
  creator_roblox_id bigint,
  creator_username text not null,
  creator_avatar_headshot text not null,
  creator_coin text not null check (creator_coin in ('blue', 'orange')),
  opponent_uuid uuid references public.rorisk_users(uuid) on delete set null,
  opponent_roblox_id bigint,
  opponent_username text,
  opponent_avatar_headshot text,
  opponent_coin text check (opponent_coin in ('blue', 'orange')),
  opponent_is_bot boolean not null default false,
  opponent_joined_at timestamptz,
  currency text not null check (currency in ('coins', 'rocoins')),
  amount bigint not null check (amount between 50 and 500000),
  state text not null default 'created' check (state in ('created', 'completed', 'cancelled')),
  winning_coin text check (winning_coin in ('blue', 'orange')),
  winner_uuid uuid references public.rorisk_users(uuid) on delete set null,
  winner_roblox_id bigint,
  winner_username text,
  winner_avatar_headshot text,
  winner_is_bot boolean not null default false,
  payout_amount bigint not null default 0 check (payout_amount >= 0),
  client_seed text not null,
  server_seed_hash text not null,
  server_seed text not null,
  nonce bigint not null default 0 check (nonce >= 0),
  eos_block_id text,
  eos_block_number bigint,
  ticket integer check (ticket between 0 and 999999),
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists rorisk_coinflip_games_state_created_idx on public.rorisk_coinflip_games (state, created_at desc);
create index if not exists rorisk_coinflip_games_creator_created_idx on public.rorisk_coinflip_games (creator_uuid, created_at desc);
create index if not exists rorisk_coinflip_games_opponent_created_idx on public.rorisk_coinflip_games (opponent_uuid, created_at desc);
create index if not exists rorisk_coinflip_games_winner_created_idx on public.rorisk_coinflip_games (winner_uuid, created_at desc);

alter table public.rorisk_coinflip_games enable row level security;
revoke all on table public.rorisk_coinflip_games from anon, authenticated;
grant select, insert, update on table public.rorisk_coinflip_games to service_role;
grant usage, select on sequence public.rorisk_coinflip_games_game_id_seq to service_role;

create or replace function public.create_rorisk_coinflip(
  p_user_uuid uuid,
  p_amount bigint,
  p_currency text,
  p_coin text,
  p_client_seed text,
  p_server_seed text,
  p_server_seed_hash text
) returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user public.rorisk_users%rowtype;
  v_game public.rorisk_coinflip_games%rowtype;
  v_balance bigint;
  v_nonce bigint;
begin
  if p_currency not in ('coins', 'rocoins') then raise exception 'The selected currency is invalid.'; end if;
  if p_coin not in ('blue', 'orange') then raise exception 'Please select blue or orange.'; end if;
  if p_amount < 50 or p_amount > 500000 then raise exception 'Your entered bet amount is invalid.'; end if;
  if encode(digest(p_server_seed, 'sha256'), 'hex') <> p_server_seed_hash then raise exception 'The coinflip seed is invalid.'; end if;

  select * into v_user from public.rorisk_users where uuid = p_user_uuid for update;
  if not found then raise exception 'Please sign in to perform this action.'; end if;
  v_balance := case when p_currency = 'coins' then coalesce(v_user.coins, 0) else coalesce(v_user.rocoins, 0) end;
  if v_balance < p_amount then raise exception 'Insufficient balance.'; end if;

  if p_currency = 'coins' then
    update public.rorisk_users set coins = coalesce(coins, 0) - p_amount where uuid = p_user_uuid returning * into v_user;
  else
    update public.rorisk_users set rocoins = coalesce(rocoins, 0) - p_amount where uuid = p_user_uuid returning * into v_user;
  end if;

  select coalesce(max(nonce) + 1, 0) into v_nonce from public.rorisk_coinflip_games where creator_uuid = p_user_uuid;
  insert into public.rorisk_coinflip_games (
    creator_uuid, creator_roblox_id, creator_username, creator_avatar_headshot, creator_coin,
    currency, amount, client_seed, server_seed_hash, server_seed, nonce
  ) values (
    v_user.uuid, v_user.roblox_id, v_user.username, v_user.avatar_headshot, p_coin,
    p_currency, p_amount, left(coalesce(p_client_seed, p_user_uuid::text), 128), p_server_seed_hash, p_server_seed, v_nonce
  )
  returning * into v_game;
  return jsonb_build_object('game', to_jsonb(v_game), 'user', to_jsonb(v_user));
end;
$$;

create or replace function public.join_rorisk_coinflip(
  p_game_uuid uuid,
  p_user_uuid uuid,
  p_bot boolean,
  p_eos_block_id text,
  p_eos_block_number bigint,
  p_ticket integer
) returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user public.rorisk_users%rowtype;
  v_creator public.rorisk_users%rowtype;
  v_winner public.rorisk_users%rowtype;
  v_game public.rorisk_coinflip_games%rowtype;
  v_join_coin text;
  v_winning_coin text;
  v_winner_uuid uuid;
  v_payout bigint;
  v_balance bigint;
begin
  select * into v_game from public.rorisk_coinflip_games where uuid = p_game_uuid for update;
  if not found then raise exception 'This coinflip game could not be found.'; end if;
  if v_game.state <> 'created' or v_game.opponent_uuid is not null or v_game.opponent_is_bot then
    if p_bot then raise exception 'This game is no longer available.';
    else raise exception 'This game is no longer available for joining.';
    end if;
  end if;
  if encode(digest(v_game.server_seed, 'sha256'), 'hex') <> v_game.server_seed_hash then raise exception 'The coinflip seed is invalid.'; end if;
  if p_eos_block_id !~ '^[a-f0-9]{64}$' or p_eos_block_number < 1 or p_ticket not between 0 and 999999 then raise exception 'The EOS fairness data is invalid.'; end if;
  v_join_coin := case when v_game.creator_coin = 'blue' then 'orange' else 'blue' end;

  select * into v_creator from public.rorisk_users where uuid = v_game.creator_uuid for update;
  if p_bot then
    if p_user_uuid <> v_game.creator_uuid then raise exception 'Only the game creator can call the bot.'; end if;
    v_user := v_creator;
  else
    if p_user_uuid = v_game.creator_uuid then raise exception 'You cannot join your own coinflip game.'; end if;
    select * into v_user from public.rorisk_users where uuid = p_user_uuid for update;
    if not found then raise exception 'Please sign in to perform this action.'; end if;
    v_balance := case when v_game.currency = 'coins' then coalesce(v_user.coins, 0) else coalesce(v_user.rocoins, 0) end;
    if v_balance < v_game.amount then raise exception 'Insufficient balance.'; end if;
    if v_game.currency = 'coins' then
      update public.rorisk_users set coins = coalesce(coins, 0) - v_game.amount where uuid = p_user_uuid returning * into v_user;
    else
      update public.rorisk_users set rocoins = coalesce(rocoins, 0) - v_game.amount where uuid = p_user_uuid returning * into v_user;
    end if;
  end if;

  v_winning_coin := case when p_ticket < 500000 then 'blue' else 'orange' end;
  if v_winning_coin = v_game.creator_coin then v_winner_uuid := v_game.creator_uuid;
  elsif not p_bot then v_winner_uuid := p_user_uuid;
  else v_winner_uuid := null;
  end if;
  v_payout := floor(v_game.amount * 1.95)::bigint;

  if v_winner_uuid is not null then
    if v_game.currency = 'coins' then
      update public.rorisk_users set coins = coalesce(coins, 0) + v_payout where uuid = v_winner_uuid returning * into v_winner;
    else
      update public.rorisk_users set rocoins = coalesce(rocoins, 0) + v_payout where uuid = v_winner_uuid returning * into v_winner;
    end if;
  end if;

  update public.rorisk_coinflip_games
  set opponent_uuid = case when p_bot then null else v_user.uuid end,
      opponent_roblox_id = case when p_bot then null else v_user.roblox_id end,
      opponent_username = case when p_bot then 'Risk Bot' else v_user.username end,
      opponent_avatar_headshot = case when p_bot then '/api/casino-images/coinflip/bot.png' else v_user.avatar_headshot end,
      opponent_coin = v_join_coin,
      opponent_is_bot = p_bot,
      opponent_joined_at = now(),
      state = 'completed', winning_coin = v_winning_coin,
      winner_uuid = v_winner_uuid,
      winner_roblox_id = case when v_winner_uuid is null then null else v_winner.roblox_id end,
      winner_username = case when v_winner_uuid is null then 'Risk Bot' else v_winner.username end,
      winner_avatar_headshot = case when v_winner_uuid is null then '/api/casino-images/coinflip/bot.png' else v_winner.avatar_headshot end,
      winner_is_bot = v_winner_uuid is null,
      eos_block_id = p_eos_block_id,
      eos_block_number = p_eos_block_number,
      ticket = p_ticket,
      payout_amount = case when v_winner_uuid is null then 0 else v_payout end,
      started_at = now(), completed_at = now() + interval '5.5 seconds', updated_at = now()
  where uuid = p_game_uuid returning * into v_game;

  select * into v_user from public.rorisk_users where uuid = p_user_uuid;
  return jsonb_build_object('game', to_jsonb(v_game), 'user', to_jsonb(v_user));
end;
$$;

revoke all on function public.create_rorisk_coinflip(uuid, bigint, text, text, text, text, text) from public, anon, authenticated;
revoke all on function public.join_rorisk_coinflip(uuid, uuid, boolean, text, bigint, integer) from public, anon, authenticated;
grant execute on function public.create_rorisk_coinflip(uuid, bigint, text, text, text, text, text) to service_role;
grant execute on function public.join_rorisk_coinflip(uuid, uuid, boolean, text, bigint, integer) to service_role;
